import type { DayOfWeek, TrackingMode } from "@gym/shared";

export interface TemplateExercise {
  exerciseName: string; // must match Exercise.name exactly (seeded from free-exercise-db)
  /** Alternate exerciseNames for the same slot — wired into the rotation pool (Plan → Rotation control). */
  alternativeNames?: string[];
  targetSets: number;
  targetRepsMin: number;
  targetRepsMax: number | null;
  restSeconds: number;
  defaultWeightKg?: number;
  trackingMode?: TrackingMode;
  targetHoldSeconds?: number;
  notes?: string;
}

export interface TemplateDay {
  dayOfWeek: DayOfWeek;
  label: string;
  isRestDay: boolean;
  exercises: TemplateExercise[];
}

/**
 * Debjyoti's 6-day aesthetic split (Push/Pull/Legs x2). Source: the personal program doc —
 * sets/reps/rest/start-weight/notes are copied verbatim where given; "X / Y" slots in the
 * source became a primary exercise + a rotation pool entry instead of two separate rows.
 */
export const DEFAULT_ROUTINE_TEMPLATE: TemplateDay[] = [
  {
    dayOfWeek: "MON",
    label: "Push A — Chest",
    isRestDay: false,
    exercises: [
      {
        exerciseName: "Barbell Bench Press - Medium Grip",
        targetSets: 4,
        targetRepsMin: 8,
        targetRepsMax: 10,
        restSeconds: 120,
        defaultWeightKg: 45,
        notes: "Main lift. Controlled, chest touch, no bounce.",
      },
      {
        exerciseName: "Incline Dumbbell Press",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 90,
        defaultWeightKg: 13,
        notes: "Builds upper chest — fuller look.",
      },
      {
        exerciseName: "Cable Crossover",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 75,
        notes: "Squeeze chest, slow.",
      },
      {
        exerciseName: "Seated Dumbbell Press",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 90,
        defaultWeightKg: 11,
      },
      {
        exerciseName: "Side Lateral Raise",
        alternativeNames: ["Cable Seated Lateral Raise"],
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 20,
        restSeconds: 60,
        defaultWeightKg: 6,
        notes: "Key for width. Slow, no swinging.",
      },
      {
        exerciseName: "Triceps Pushdown - Rope Attachment",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 75,
      },
      {
        exerciseName: "Cable Rope Overhead Triceps Extension",
        targetSets: 2,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 60,
      },
      {
        exerciseName: "Cable Crunch",
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 15,
        restSeconds: 45,
        notes: "Abs finisher — quick 2-3 min.",
      },
    ],
  },
  {
    dayOfWeek: "TUE",
    label: "Pull A — Back Width",
    isRestDay: false,
    exercises: [
      {
        exerciseName: "Wide-Grip Lat Pulldown",
        targetSets: 4,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 120,
        notes: "Pull to upper chest, lead with elbows. Builds the V.",
      },
      {
        exerciseName: "Seated Cable Rows",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 90,
        notes: "Squeeze shoulder blades.",
      },
      {
        exerciseName: "One-Arm Dumbbell Row",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 90,
        defaultWeightKg: 15,
        notes: "Full stretch + squeeze, per arm.",
      },
      {
        exerciseName: "Face Pull",
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 20,
        restSeconds: 60,
        notes: "Rear delts + posture. Don't skip.",
      },
      {
        exerciseName: "Hammer Curls",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 60,
        defaultWeightKg: 12,
        notes: "Builds arm thickness.",
      },
      {
        exerciseName: "Incline Dumbbell Curl",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 60,
        defaultWeightKg: 9,
        notes: "Bicep peak.",
      },
      {
        exerciseName: "Hanging Leg Raise",
        alternativeNames: ["Flat Bench Lying Leg Raise"],
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 60,
        notes: "Abs.",
      },
    ],
  },
  {
    dayOfWeek: "WED",
    label: "Legs A — Quads",
    isRestDay: false,
    exercises: [
      {
        exerciseName: "Leg Press",
        targetSets: 4,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 120,
        notes: "Feet mid-platform.",
      },
      {
        exerciseName: "Goblet Squat",
        alternativeNames: ["Hack Squat"],
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 120,
        notes: "Depth over weight — start light.",
      },
      {
        exerciseName: "Leg Extensions",
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 15,
        restSeconds: 75,
        notes: "Quad finisher, squeeze top.",
      },
      {
        exerciseName: "Romanian Deadlift",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 120,
        defaultWeightKg: 45,
        notes: "Hamstrings, slight knee bend, flat back.",
      },
      {
        exerciseName: "Lying Leg Curls",
        alternativeNames: ["Seated Leg Curl"],
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 75,
      },
      {
        exerciseName: "Standing Calf Raises",
        targetSets: 4,
        targetRepsMin: 15,
        targetRepsMax: 20,
        restSeconds: 60,
        notes: "Full stretch bottom, full squeeze top.",
      },
      {
        exerciseName: "Cable Crunch",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 45,
        notes: "Abs with weight.",
      },
    ],
  },
  {
    dayOfWeek: "THU",
    label: "Push B — Shoulders",
    isRestDay: false,
    exercises: [
      {
        exerciseName: "Seated Dumbbell Press",
        targetSets: 4,
        targetRepsMin: 8,
        targetRepsMax: 10,
        restSeconds: 120,
        defaultWeightKg: 12,
        notes: "Main shoulder builder.",
      },
      {
        exerciseName: "Side Lateral Raise",
        alternativeNames: ["Cable Seated Lateral Raise"],
        targetSets: 4,
        targetRepsMin: 15,
        targetRepsMax: 20,
        restSeconds: 60,
        notes: "Extra volume — this is your width maker.",
      },
      {
        exerciseName: "Incline Dumbbell Press",
        alternativeNames: ["Barbell Incline Bench Press - Medium Grip"],
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 90,
        notes: "Upper chest.",
      },
      {
        exerciseName: "Leverage Chest Press",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 90,
      },
      {
        exerciseName: "Reverse Machine Flyes",
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 20,
        restSeconds: 60,
        notes: "Rounds out shoulders.",
      },
      {
        exerciseName: "Dip Machine",
        alternativeNames: ["Bench Dips"],
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 75,
      },
      {
        exerciseName: "Triceps Pushdown",
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 15,
        restSeconds: 75,
        notes: "Straight bar.",
      },
      {
        exerciseName: "Hanging Leg Raise",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 45,
        notes: "Abs finisher — quick 2-3 min.",
      },
    ],
  },
  {
    dayOfWeek: "FRI",
    label: "Pull B — Back Thickness + Arms",
    isRestDay: false,
    exercises: [
      {
        exerciseName: "Bent Over Barbell Row",
        alternativeNames: ["T-Bar Row with Handle"],
        targetSets: 4,
        targetRepsMin: 8,
        targetRepsMax: 10,
        restSeconds: 120,
        defaultWeightKg: 40,
        notes: "Thickness. Strict, no jerking.",
      },
      {
        exerciseName: "Close-Grip Front Lat Pulldown",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 90,
      },
      {
        exerciseName: "Elevated Cable Rows",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        restSeconds: 90,
        notes: "Wide grip.",
      },
      {
        exerciseName: "Dumbbell Shrug",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 60,
        defaultWeightKg: 15,
        notes: "Traps, hold 1 sec at top.",
      },
      {
        exerciseName: "Barbell Curl",
        alternativeNames: ["EZ-Bar Curl"],
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 60,
        defaultWeightKg: 17.5,
      },
      {
        exerciseName: "Preacher Curl",
        alternativeNames: ["Concentration Curls"],
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 60,
      },
      {
        exerciseName: "Plank",
        targetSets: 3,
        targetRepsMin: 1,
        targetRepsMax: null,
        restSeconds: 60,
        trackingMode: "TIME",
        targetHoldSeconds: 52,
        notes: "Core.",
      },
    ],
  },
  {
    dayOfWeek: "SAT",
    label: "Legs B — Hamstrings + Glutes",
    isRestDay: false,
    exercises: [
      {
        exerciseName: "Romanian Deadlift",
        targetSets: 4,
        targetRepsMin: 8,
        targetRepsMax: 10,
        restSeconds: 120,
        defaultWeightKg: 50,
        notes: "Main posterior lift.",
      },
      {
        exerciseName: "Hack Squat",
        alternativeNames: ["Leg Press"],
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        restSeconds: 120,
        notes: "High feet = more hams/glutes.",
      },
      {
        exerciseName: "Lying Leg Curls",
        targetSets: 4,
        targetRepsMin: 12,
        targetRepsMax: 15,
        restSeconds: 75,
      },
      {
        exerciseName: "Bodyweight Walking Lunge",
        alternativeNames: ["Crossover Reverse Lunge"],
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        restSeconds: 75,
        notes: "Per leg.",
      },
      {
        exerciseName: "Seated Calf Raise",
        targetSets: 4,
        targetRepsMin: 15,
        targetRepsMax: 20,
        restSeconds: 60,
      },
      {
        exerciseName: "Cable Crunch",
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 15,
        restSeconds: 45,
        notes: "Abs.",
      },
      {
        exerciseName: "Russian Twist",
        targetSets: 3,
        targetRepsMin: 20,
        targetRepsMax: null,
        restSeconds: 45,
        notes: "20 total, both sides — obliques.",
      },
    ],
  },
  {
    dayOfWeek: "SUN",
    label: "Rest Day",
    isRestDay: true,
    exercises: [],
  },
];
